name: Nix Flake Check

on: [push, pull_request, workflow_dispatch]

jobs:
  tests:
    name: Check expressions
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          install_url: https://nixos.org/nix/install
          extra_nix_config: |
            auto-optimise-store = true
      - run: nix build
      - run: nix flake check
