name: update-flake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v23

      - name: "Update flake.lock ❄️"
        run: |
          nix flake update

      - name: "Commit and push"
        uses: EndBug/add-and-commit@v9
        with:
          add: "flake.lock"
          default_author: github_actions
          message: "chore: update flake.lock"
        
