name: update-flake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update-flake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.0.0

      - name: "Update flake.lock"
        run: |
          nix flake update

      - name: "Commit and push"
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add flake.lock
          git commit -m "chore: update flake.lock"
          git push
        
