-- Stolen from rohankid1/cachy-dotfiles
-- ----------
-- Animations
-- Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
-- ----------

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.curve("linear", { type = "bezier", points = { { 0.0, 0.0 }, { 1.0, 1.0 } } })
hl.curve("myBezier", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("overshot", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.1 } } })
hl.curve("cubic", { type = "bezier", points = { { 0.54, 0.22 }, { 0.07, 0.74 } } })
hl.curve("overshotCircle", { type = "bezier", points = { { 0.175, 0.885 }, { 0.32, 1.275 } } })
hl.curve("md3_standard", { type = "bezier", points = { { 0.2, 0.0 }, { 0, 1.0 } } })
hl.curve("bounce", { type = "bezier", points = { { 1, 1.6 }, { 0.1, 0.85 } } })
hl.curve("decel", { type = "bezier", points = { { 0.05, 0.7 }, { 0.1, 1 } } })
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 3,
    bezier = "bounce",
    style = "popin 23%",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 2,
    bezier = "md3_standard",
    style = "slide",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 10,
    bezier = "overshot",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3,
    bezier = "linear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 4,
    bezier = "decel",
    style = "slidefadevert",
})
hl.config({
    animations = {
        enabled = true,
        -- bezier = myBezier, 0.05, 0.9, 0.1, 1.05
        -- bezier = custom, 0.72, 0.04, 0.06, 0.84
        --     
        -- animation = windows, 1, 7, myBezier
        -- animation = windowsIn, 1, 7, default, popin
        -- animation = windowsOut, 1, 7, default, slide
        -- animation = border, 1, 10, default
        -- animation = borderangle, 1, 8, default
        -- animation = fade, 1, 7, default
        -- animation = workspaces, 1, 6, default, slide # or slidevert
        -- animation = specialWorkspace, 1, 6, myBezier, slidefadevert
        --animation = windowsOut, 1, 7, bounce, slide
    },
})

