
source = ~/.config/hypr/macchiato.conf

background {
	path = screenshot
	blur_passes = 2
}

label {
	text = cmd[update:1000] date +"%-I:%M%p"
	font_size = 80
	font_family = Ubuntu Mono Bold
	color = $text

	position = 0, 130
	halign = center
	valign = center
}

label {
	text = Welcome back, $USER
	color = $subtext1
	font_size = 14
	font_family = Ubuntu Mono

	position = 2, 20
	halign = center
	valign = center
}

input-field {
	size = 10%, 4%	
	outer_color = $mauve
	inner_color = $surface2
	fail_color = $red
	font_color = $text
	font_family = JetBrainsMono Nerd Font
	fade_on_empty = false

	position = 0, -30
	halign = center
	valign = center
}
