--
-- Please note not all available settings / options are set here.
-- For a full list, see the wiki
--

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "eDP-1",
    mode = "1920x1080@60",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "desc:Acer Technologies ED242QR A TBDAA0023900",
    mode = "preferred",
    position = "0x0",
    scale = "1",
})

hl.monitor({
    output = "desc:Envision Peripherals Inc L19W898 K768ACA013474",
    mode = "preferred",
    position = "auto-left",
    scale = "1",
})

-- Wayland stuff

-- Processes

-- Script to launch applications on certain workspaces on launch only
--exec-once=bash ~/.config/hypr/scripts/init_apps

-- Source: ~/.config/hypr/macchiato.conf — convert this file to Lua and ensure it is on Lua's package.path.
local palette = require("macchiato")

-- See https://wiki.hyprland.org/Configuring/Keywords/ for more

-- For all categories, see https://wiki.hyprland.org/Configuring/Variables/

-- Source: ~/.config/hypr/animations.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("animations")

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})

local mainMod = "SUPER"

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd("kitty -e zsh"))
hl.bind(mainMod .. " + C", hl.dsp.window.close())
hl.bind(mainMod .. " + M", hl.dsp.exit())
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd("dolphin"))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + R", hl.dsp.exec_cmd("wofi --show drun"))
hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
hl.bind(mainMod .. " + O", hl.dsp.layout("togglesplit, "))
hl.bind(mainMod .. " + F", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }))
hl.bind(mainMod .. " + H", hl.dsp.exec_cmd("systemctl suspend"))
hl.bind("Print", hl.dsp.exec_cmd("grim"))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" ~/Pictures/Screenshots/$(date +'%s_grim.png')"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("kitty -e bash ~/.config/hypr/scripts/set-wallpaper"))
hl.bind("ALT + TAB", hl.dsp.focus({ workspace = "previous" }))
hl.bind(mainMod .. " + N", hl.dsp.focus({ workspace = "empty" }))

hl.bind(mainMod .. " + I", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + J", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + K", hl.dsp.window.move({ direction = "d" }))
hl.bind(mainMod .. " + L", hl.dsp.window.move({ direction = "r" }))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1 }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2 }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3 }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4 }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5 }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6 }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7 }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8 }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9 }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10 }))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("xf86monbrightnessup", hl.dsp.exec_cmd("brightnessctl set +10%"))
hl.bind("xf86monbrightnessdown", hl.dsp.exec_cmd("brightnessctl set 10%-"))
hl.bind("xf86audioraisevolume", hl.dsp.exec_cmd("pamixer -i 5"))
hl.bind("xf86audiolowervolume", hl.dsp.exec_cmd("pamixer -d 5"))
hl.bind("xf86audiomute", hl.dsp.exec_cmd("pamixer -t"))
hl.bind("xf86poweroff", hl.dsp.exec_cmd("adios --systemd"))

hl.window_rule({
    match = {
        class = "kitty",
    },
    opacity = "0.8 1 0.8",
})

hl.window_rule({
    match = {
        class = "kitty",
        float = 1,
    },
    max_size = "800 600",
})

hl.window_rule({
    match = {
        class = "polkit-kde-authentication-agent-1",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = "auto-cpufreq",
    },
    float = true,
})

hl.window_rule({
    match = {
        class = ".*",
    },
    idle_inhibit = "fullscreen",
})

hl.layer_rule({
    match = { namespace = "blur 1" },
    -- TODO: manual review — unmapped layer rule: "match:namespace bar0"
    -- TODO: manual review — unmapped layer rule: "match:namespace media"
    -- TODO: manual review — unmapped layer rule: "match:namespace controlcenter"
})

hl.config({
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "",
        kb_rules = "",
        follow_mouse = 1,
        touchpad = {
            natural_scroll = false,
        },
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
    },
    general = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        gaps_in = 3,
		gaps_out = {
			top = 0,
			left = 10
		},
        border_size = 2,
        col = {
            inactive_border = "rgba(595959aa)",
			active_border = {
				colors = { palette.mauve, palette.blue },
				angle = 90
			},
        },
        layout = "dwindle",
    },
    misc = {
        disable_hyprland_logo = true,
    },
    decoration = {
        -- See https://wiki.hyprland.org/Configuring/Variables/ for more
        rounding = 5,
        blur = {
            enabled = true,
            size = 8,
            passes = 4,
            ignore_opacity = true,
            new_optimizations = true,
            noise = 0.01,
            contrast = 0.9,
            brightness = 0.8,
            xray = true,
        },
        shadow = {
            enabled = false,
            range = 4,
            render_power = 3,
        },
    },
    -- animations {
    --     enabled = yes
    --     # Some default animations, see https://wiki.hyprland.org/Configuring/Animations/ for more
    --     bezier = myBezier, 0.05, 0.9, 0.1, 1.05
    --     bezier = md3_decel, 0.05, 0.7, 0.1, 1
    --     animation=windowsIn,1,6,md3_decel,slide
    --     animation=windowsOut,1,6,md3_decel,slide
    --     animation=windowsMove,1,6,md3_decel,slide
    --     animation=fade,1,10,md3_decel
    --     animation=workspaces,1,7,md3_decel,slide
    --     animation=specialWorkspace,1,8,md3_decel,slide
    --     # animation = windows, 1, 7, myBezier
    --     # animation = windowsOut, 1, 7, default, popin 80%
    --     # animation = border, 1, 10, default
    --     # animation = fade, 1, 7, default
    --     # animation = workspaces, 1, 6, default
    -- }
    -- Animations
    dwindle = {
        -- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
        preserve_split = true, -- you probably want this
    },
    master = {
        -- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
        new_status = "master",
    },
    xwayland = {
        force_zero_scaling = true,
    },
    -- Example windowrule v1
    -- windowrule = float, ^(kitty)$
    -- Example windowrule v2
    -- windowrulev2 = float,class:^(kitty)$,title:^(kitty)$
    -- See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
    -- See https://wiki.hyprland.org/Configuring/Keywords/ for more
    -- Example binds, see https://wiki.hyprland.org/Configuring/Binds/ for more
    -- Move window binds
    -- Move focus with mainMod + arrow keys
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9]
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Laptop binds
    --Window rules
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("~/polkit-kde-authentication-agent-1")
    hl.exec_cmd("saturn &")
    hl.exec_cmd("hyprpaper &")
    hl.exec_cmd("hypridle")
end)

